### ISSUE TITLE
how to convert from JSON to querystring

### ISSUE THREAD

**Issue by vinnitu** [google/go-querystring#18]
// data from client rpc request in bytes

data := []byte(`{
  "a": {
     "b": 1
  },
  "c": [1, 2, 3]
}`)

Now we need make url request with querystring from this json

How can we do it with your module if we don't know struct exactly?

**Comment by willnorris** [comment]
There's no really straightforward way to do this with go-querystring, since as you state, you don't necessarily know that actual data structure.  Even if you were able to use reflection to force it to work, I don't imagine you'd be able to really take advantage of what go-querystring offers, which is per-field customization of how values are encoded.  You'd probably be better off just iterating over the JSON structure and populating a `url.Values` as you go.

Of course, this is also 4+ years old, so I'm sure you've long since moved on.  I'll go ahead and close this, but happy to continue to discussing if anyone cares to.
