### ISSUE TITLE
Structure fields original order messed up

### ISSUE THREAD

**Issue by achesco** [google/go-querystring#61]
Hi
Thanks for your work!

Code sample from README states:

```go
type Options struct {
  Query   string `url:"q"`
  ShowAll bool   `url:"all"`
  Page    int    `url:"page"`
}
opt := Options{ "foo", true, 2 }
v, _ := query.Values(opt)
fmt.Print(v.Encode()) // will output: "q=foo&all=true&page=2"
```
Question is about this: `fmt.Print(v.Encode()) // will output: "q=foo&all=true&page=2"`

But the actual output is `all=true&page=2&q=foo` for me. It could be critical, for example, if you need to generate payload based signature, since `json.Marshal(opt)` keeps original keys order:

```go
type Options struct {
	Query   string `url:"q" json:"q"`
	ShowAll bool   `url:"all" json:"all"`
	Page    int    `url:"page" json:"page"`
}
opt := Options{ "foo", true, 2 }
v, _ := json.Marshal(opt)
fmt.Print(string(js)) // outputs {"q":"foo","all":true,"page":2}
```

**Comment by willnorris** [comment]
Thanks for the report.  I suspect that this is because `url.Values` is a `map[string][]string`, whose key access is by definition unordered.  There's not really much go-querystring can do about that.  That's a good callout though, and we could certainly add a reminder in the docs somewhere that if stable ordering is needed, then the caller will need to handle that.  I haven't looked, but I would imagine `encoding/json` does have this problem because it's using its own internal data structures rather than maps.

I'm curious though, is this causing problems in practice?  You mention signatures, but I would assume that signatures would be generated on the output of encoding the `url.Values`, so as long as you're generating the signature on the same encoding that is passed in a URL, then the ordering shouldn't matter.  And I don't say that to dismiss the concern... only to better understand the severity.

**Comment by achesco** [comment]
I wouldn't insist on "severity" actually :) My practical case is about the Binance's API, they ask for a request body payload to be accompanied by a signature header calculated on the string represented by `param1=value1&param2=value2` pairs of actual JSON payload. Possible workaround in my case is to use a query string to pass all the params I need. I could imagine this could be a real issue in a similar situation but without query params support.

Another type of problem I could think about is when values of the params with the same names are overridden by the latter ones under some circumstances... not critical either.
