### ISSUE TITLE
Parsing?

### ISSUE THREAD

**Issue by maliqq** [google/go-querystring#7]
Golang's standard net/url parse builds flat query params:

```
?a[]=1&a[]=2&b[c]=d
```

results:

```
map[string][]string{
"a[]": []string{"1", "2"},
"b[c]": []string{"d"}
}
```

what is needed:

```
map[string]interface{}{
"a": []string{"1", "2"},
"b": map[string]string{"c": "d"}
}
```

**Comment by shurcooL** [comment]
> As for unmarshalling, that's outside the initial scope of this library. It could of course be added, but at that point, why not just use http://www.gorillatoolkit.org/pkg/schema ?

I would like unmarshalling/parsing too. I don't think I can use gorilla/schema because:

> Package gorilla/schema fills a struct with form values.

But I want to work with url queries, because this is for GET requests.

My need for this right now is weak, I just have a `// TODO: Automate this conversion process.` comment. If my need becomes stronger, I will work on implementing this, unless I'm missing something and parsing isn't neccessary.

**Comment by Abramovic** [comment]
@shurcooL  - you should be able to use gorilla/schema with query params 

This works for me: 

```go

import (
	"fmt"
	"net/http"
	"github.com/gorilla/schema"
)

type Person struct {
	Name  string `schema:"name"`  // custom name
	Admin bool   `schema:"-"`     // this field is never set
}

func MyHandler(w http.ResponseWriter, r *http.Request) {
	var person Person
	decoder := schema.NewDecoder()
	if err := decoder.Decode(&person, r.URL.Query()); err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(person)
}
```

**Comment by shurcooL** [comment]
Thanks for the heads up @Abramovic, I will give that a shot.

**Comment by shurcooL** [comment]
Following up here. I gave the above a shot, and it seems to work well, see https://github.com/shurcooL/home/pull/5.

The current description of the `github.com/gorilla/schema` package says:

> Package gorilla/schema fills a struct with form values.

Which is why I didn't expect I could use it to parse queries. I think should be updated to mention that it works well on parsing query parameters as well as form values.

However, it turns out that package does not currently have support for the opposite direction, for encoding a struct, which is issue https://github.com/gorilla/schema/issues/44. (There is a PR https://github.com/gorilla/schema/pull/46 to implement that, which is close but not yet merged.)

So the current situation is best described via the following table: 

| | `gorilla/schema` | `google/go-querystring/query` |
--|------------------|----------------------------
Decode Form to Struct | ✅ | ❌
Decode Query to Struct | ✅ | ❌
Encode Struct to Form | ❌ | ❌
Encode Struct to Query | ❌ | ✅ 

As an observation, to me, it'd be valuable to have a library that can go in both directions, because of the implicit guarantee that it should be a stable mapping without surprises when doing both encoding/decoding.

**Comment by willnorris** [comment]
I'd be happy to just have go-querystring (or some variation of it) merged into gorilla/schema if they're open to it.

**Comment by kisielk** [comment]
That sounds like a good idea to me. It would be nice to have one canonical library for this type of thing.

**Comment by hetiansu5** [comment]
an URL Query string Encoder and Parser. It works well.

https://github.com/hetiansu5/urlquery

**Comment by willnorris** [comment]
Closing this, since this library is basically done and I'm really only doing basic maintenance.  I did add an alternatives section to the README, however, with links to other libraries that do this: https://github.com/google/go-querystring#alternatives
